// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/todo.proto

package grpc_impl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MdService_CreateMd_FullMethodName = "/proto.MdService/CreateMd"
)

// MdServiceClient is the client API for MdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MdServiceClient interface {
	CreateMd(ctx context.Context, in *NewMd, opts ...grpc.CallOption) (*Md, error)
}

type mdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMdServiceClient(cc grpc.ClientConnInterface) MdServiceClient {
	return &mdServiceClient{cc}
}

func (c *mdServiceClient) CreateMd(ctx context.Context, in *NewMd, opts ...grpc.CallOption) (*Md, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Md)
	err := c.cc.Invoke(ctx, MdService_CreateMd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MdServiceServer is the server API for MdService service.
// All implementations must embed UnimplementedMdServiceServer
// for forward compatibility.
type MdServiceServer interface {
	CreateMd(context.Context, *NewMd) (*Md, error)
	mustEmbedUnimplementedMdServiceServer()
}

// UnimplementedMdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMdServiceServer struct{}

func (UnimplementedMdServiceServer) CreateMd(context.Context, *NewMd) (*Md, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMd not implemented")
}
func (UnimplementedMdServiceServer) mustEmbedUnimplementedMdServiceServer() {}
func (UnimplementedMdServiceServer) testEmbeddedByValue()                   {}

// UnsafeMdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MdServiceServer will
// result in compilation errors.
type UnsafeMdServiceServer interface {
	mustEmbedUnimplementedMdServiceServer()
}

func RegisterMdServiceServer(s grpc.ServiceRegistrar, srv MdServiceServer) {
	// If the following call pancis, it indicates UnimplementedMdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MdService_ServiceDesc, srv)
}

func _MdService_CreateMd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMd)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdServiceServer).CreateMd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdService_CreateMd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdServiceServer).CreateMd(ctx, req.(*NewMd))
	}
	return interceptor(ctx, in, info, handler)
}

// MdService_ServiceDesc is the grpc.ServiceDesc for MdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MdService",
	HandlerType: (*MdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMd",
			Handler:    _MdService_CreateMd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/todo.proto",
}
